

export const data = [
	{
		id: 1,
		src: require('./img/parisTour.jpg'),
		name: 'Best Of Paris In 7 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '$1,995',
		text: "Paris is synonymous with the finest things that culture can offer — in art, fashion, food, literature, and ideas. On this tour,your Paris- savvy Rick Steves guide will immerse you in the very best of the City.the masterpiece-packed Louvre and Orsay museums, resilient Notre-Dame Cathedral, exquisite Sainte-Chapelle, and extravagant Palace of Versailles. You'll also enjoy guided neighborhood walks through the city's historic heart as well as quieter moments to slow down and savor the city's intimate cafés, colorful markets, and joie de vivre. Join us for the Best of Paris in 7 Days!",
		link: 'https://en.wikipedia.org/wiki/Paris',
	},
	{
		id: 2,
		src: require('./img/Obudu-Cattle-Ranch-1.jpg'),
		name: 'Best Of Obudu In 10 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '#200,000',
		text: 'If you are in search of fun, adventure, and the bliss of nature, then Obudu mountain resort is the perfect place for you. This scenic paradise is located in the deep tropical forests and uplands of Calabar, Cross River state in Nigeria.The resort is picturesque and full of natural vegetation, an ideal place for a romantic getaway, family time, or boys’ hangout. The resort also known as Obudu cattle ranch has a temperate climate and is about 45 miles from the Cameroonian border. ',
		link: 'https://traveltank.com/blog/obudu-mountain-resort-nigerias-scenic-paradise/',
	},

	{
		id: 3,
		src: require('./img/irelandTour.jpeg'),
		name: 'Best Of Ireland In 14 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '$3,895',
		text: "Rick Steve's Best of Ireland tour kicks off with the best of Dublin, followed by Ireland's must-see historical sites, charming towns, music-filled pubs, and seaside getaways — including Kinsale, the Dingle Peninsula, the Cliffs of Moher, the Aran Islands, Galway, Connemara, Giant's Causeway, and the compelling city of Belfast. All along the way, Rick's guides will share their stories to draw you in to the Emerald Isle, and the friendliness of the people will surely steal your heart. Join us for the Best of Ireland in 14 Days!.",
		link: 'https://en.wikipedia.org/wiki/Ireland',
	},
	{
		id: 4,
		src: require('./img/lagos.jpg'),
		name: 'Best Of Lagos In 2 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '#50,000',
		text: 'Lagos for a fun and happening day out with the family.  Lagos experiences warm weather throughout the year, with the relatively cooler months being between June to September. The city receives a moderate amount of rainfall throughout the year, with the monsoon months concentrated between May to July.',
		link: 'https://www.thrillophilia.com/cities/lagos',
	},
	{
		id: 5,
		src: require('./img/viennaTour.jpeg'),
		name: 'Best Of Salzburg & Vienna In 8 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '$2,695',
		text: "Let's go where classical music, towering castles, and the-hills-are-alive scenery welcome you to the gemütlichkeit of Bavaria and opulence of Austria's Golden Age.Your Rick Steves guide will bring this region's rich history and culture to life in festive Munich, Baroque Salzburg, sparkling Lake Hallstatt, monastic Melk, the blue Danube, and royal Vienna — with cozy villages and alpine vistas all along the way. Join us for the Best of Munich, Salzburg & Vienna in 8 Days! ",
		link: 'https://en.wikipedia.org/wiki/Vienna',
	},
	{
		id: 6,
		src: require('./img/italyTour.jpeg'),
		name: 'Best Of Rome In 7 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '$2,095',
		text: "Our Rome tour serves up Europe's most intoxicating brew of dazzling art, earth-shaking history, and city life with style. On this Rome vacation, your tour guide will resurrect the grandeur of ancient Rome's Colosseum, Forum, Pantheon, and nearby Ostia Antica. From the Renaissance and Baroque eras, you'll marvel at St. Peter's Basilica, the Vatican Museums, Sistine Chapel, and Borghese Gallery. You'll also enjoy today's Rome, with neighborhood walking tours, memorable restaurants, and time to explore on your own. Join us for the Best of Rome in 7 Days! ",
		link: 'https://en.wikipedia.org/wiki/Italy',
	},
	{
		id: 7,
		src: require('./img/polandTour.jpeg'),
		name: 'Best Of Poland In 10 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '$2,595',
		text: "Starting in the colorful port city of Gdańsk, you'll escape the crowds and embrace the understated elegance of ready-for-prime-time Poland for 10 days.With an expert Rick Steves guide at your side, you'll experience mighty Malbork castle, the cobbly-cute village of Toruń, Poland's contemporary capital of Warsaw, the spiritual Jasna Góra Monastery, and charming Kraków — Poland's finest city. In this land of surprises — so trendy and hip, yet steeped in history — there's so much to discover. Join us for the Best of Poland in 10 Days! ",
		link: 'https://www.britannica.com/place/Poland',
	},
	{
		id: 8,
		src: require('./img/ghana.jpg'),
		name: 'Best Of Ghana In 3 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '#150,000',
		text: " find out more about the history of Ghana's independence while having a fun tour, the Kwame Nkrumah Memorial Park should be among the top list of places you should visit. It is also home to some rare artefacts that are related to Ghana independence. ",
		link: 'https://momaa.org/directory/kwame-nkrumah-memorial-park/',
	},
	{
		id: 9,
		src: require('./img/great wall of china.jpg'),
		name: 'Best Of china In 7 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '$1,500',
		text: 'The Great Wall of China (traditional Chinese: 萬里長城; simplified Chinese: 万里长城; pinyin: Wànlǐ Chángchéng) is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe,tour round china embrace the warm nature and sunlight by china.',
		link: 'https://artsandculture.google.com/story/10-things-to-know-about-the-great-wall-of-china-simatai-great-wall-tourist-area/8wXxFCy7pu2HWA?hl=en',
	},
	{
		id: 10,
		src: require('./img/rwanda.jpg'),
		name: 'Best Of Rwanda In 7 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '$1,500',
		text: 'Looking for somewhere peaceful look no further The excellent Ethnographic Museum, also known as the National Museum, houses perhaps the finest ethnographic collection in Africa. Displays of traditional artefacts and antique monochrome photographs provide an insight in to the pre-colonial era as well as Rwanda’s transition into a modern state. ',
		link: 'https://www.visitrwanda.com/destinations/huye/',
	},
	{
		id: 11,
		src: require('./img/sa.jpg'),
		name: 'Best Of South Africa In 10 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '$2,000',
		text: ' South Africa so peaceful and nice place to visit You will be in awe of Drakensberg’s famous mountain peaks like Giants Castle and Cathedral Peak, but you will also be drawn to its foothills that are filled with incredible waterfalls, rock pools, mountain streams and prehistoric caves.',
		link: 'https://www.travelanddestinations.com/top-places-to-visit-in-south-africa/',
	},
	{
		id: 12,
		src: require('./img/moza.jpg'),
		name: 'Best Of Island of Mozambique In 7 Days Tour',
		icon: require('./img/arrow-right-square-fill.svg'),
		price: '$2,000',
		text: 'The Island of Mozambique lies off northern Mozambique, between the Mozambique Channel and Mossuril Bay, and is part of Nampula Province. Prior to 1898, it was the capital of colonial Portuguese East Africa. ',
		link: 'https://whc.unesco.org/en/list/599/',
	},
];
